#!/usr/bin/env python3
"""
Summarize SISBRA->FDSN match outcomes by SISBRA source/agency.

Reads event bundles generated by step02 (event.json files) and reports:
- global status counts
- no_match concentration by source agency
- CSV summary for sharing/reporting
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
import re
from collections import Counter, defaultdict


def _extract_agency_tag(source_comments: str) -> str:
    s = (source_comments or "").strip()
    if not s:
        return "UNKNOWN"
    m = re.search(r"\(([^)]+)\)", s)
    if m:
        tag = m.group(1).strip()
    else:
        tag = s.split()[0].strip()
    if not tag:
        return "UNKNOWN"
    return tag.upper()


def _load_event_jsons(out_root: str) -> list[tuple[str, dict]]:
    pattern = os.path.join(out_root, "*", "event.json")
    files = sorted(glob.glob(pattern))
    out: list[tuple[str, dict]] = []
    for p in files:
        try:
            with open(p, "r", encoding="utf-8") as f:
                out.append((p, json.load(f)))
        except Exception:
            continue
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Summarize no_match by SISBRA source/agency.")
    ap.add_argument("--out-root", default="data/sisbra_all_w24", help="Run output root containing */event.json.")
    ap.add_argument(
        "--out-csv",
        default="outputs/no_match_agency_summary.csv",
        help="CSV with per-agency summary.",
    )
    ap.add_argument(
        "--out-no-match-csv",
        default="outputs/no_match_events.csv",
        help="CSV with one row per no_match event.",
    )
    ap.add_argument("--top", type=int, default=20, help="Top agencies to print by no_match.")
    args = ap.parse_args()

    items = _load_event_jsons(args.out_root)
    if not items:
        raise SystemExit(f"No event.json found under: {args.out_root}")

    global_counts = Counter()
    by_agency: dict[str, Counter] = defaultdict(Counter)
    matched_picks_sum = Counter()
    matched_picks_n = Counter()
    matched_zero_picks = Counter()
    no_match_rows = []

    for path, payload in items:
        status = str(payload.get("match_status", "") or "unknown").strip().lower()
        sis = payload.get("sisbra") or {}
        source_comments = str(sis.get("source_comments", "") or "")
        agency = _extract_agency_tag(source_comments)
        picks_count = len(payload.get("picks") or [])

        global_counts[status] += 1
        by_agency[agency][status] += 1
        by_agency[agency]["total"] += 1

        if status == "matched":
            matched_picks_sum[agency] += picks_count
            matched_picks_n[agency] += 1
            if picks_count == 0:
                matched_zero_picks[agency] += 1
        elif status == "no_match":
            no_match_rows.append(
                {
                    "folder": os.path.basename(os.path.dirname(path)),
                    "sisbra_time": sis.get("origin_time", ""),
                    "sisbra_lat": sis.get("latitude", ""),
                    "sisbra_lon": sis.get("longitude", ""),
                    "sisbra_mag": sis.get("magnitude", ""),
                    "agency": agency,
                    "source_comments": source_comments,
                    "state": sis.get("state", ""),
                    "localities": sis.get("localities", ""),
                }
            )

    summary_rows = []
    for agency, c in by_agency.items():
        total = c.get("total", 0)
        matched = c.get("matched", 0)
        no_match = c.get("no_match", 0)
        ambiguous = c.get("ambiguous", 0)
        error = c.get("error", 0)
        mean_picks = (
            float(matched_picks_sum[agency]) / float(matched_picks_n[agency])
            if matched_picks_n[agency] > 0
            else 0.0
        )
        summary_rows.append(
            {
                "agency": agency,
                "total": total,
                "matched": matched,
                "no_match": no_match,
                "ambiguous": ambiguous,
                "error": error,
                "no_match_rate_pct": round((100.0 * no_match / total) if total else 0.0, 3),
                "matched_rate_pct": round((100.0 * matched / total) if total else 0.0, 3),
                "matched_zero_picks": matched_zero_picks.get(agency, 0),
                "matched_mean_picks": round(mean_picks, 3),
            }
        )

    summary_rows.sort(key=lambda r: (-r["no_match"], -r["total"], r["agency"]))
    no_match_rows.sort(key=lambda r: (r["agency"], r["sisbra_time"]))

    os.makedirs(os.path.dirname(args.out_csv) or ".", exist_ok=True)
    if summary_rows:
        with open(args.out_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
            w.writeheader()
            w.writerows(summary_rows)

    if no_match_rows:
        with open(args.out_no_match_csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(no_match_rows[0].keys()))
            w.writeheader()
            w.writerows(no_match_rows)

    total_bundles = sum(global_counts.values())
    print(f"out_root={args.out_root}")
    print(f"bundles={total_bundles}")
    print(f"global_counts={dict(global_counts)}")
    print(f"summary_csv={args.out_csv}")
    print(f"no_match_csv={args.out_no_match_csv}")

    print("\nTop no_match by agency:")
    for row in summary_rows[: max(0, args.top)]:
        if row["no_match"] <= 0:
            continue
        print(
            f"- {row['agency']}: no_match={row['no_match']} total={row['total']} "
            f"rate={row['no_match_rate_pct']}% matched={row['matched']}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
